# Producción

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

spring.mvc.dispatch-options-request=true

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}

whatsapp.verify.token=${WHATSAPP_VERIFY_TOKEN}
whatsapp.access.token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.phone.number.id=${WHATSAPP_PHONE_NUMBER_ID}

asesor.telefono=${ASESOR_TELEFONO}