spring.datasource.url=jdbc:mysql://localhost:3306/estampaider
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# CORS
spring.mvc.dispatch-options-request=true

# WhatsApp
whatsapp.verify.token=estampaider_token_123
whatsapp.access.token=EAASnxhVhq6UBRKAKfIq6Efz2YKSXqOXmbrweZCRFZCvbTIjLjYQJth3Bk8ipZAhajvwA2es6uYo6yd52MEhiSMzqVLghW5GINDCFzomHpNP1EEPl60uUZAJaNU8AnkK1nphwuGGyxs8l2J4Q1zRkmZBZCJM02bxYPVOSQqsZBljNB5ZB8XnQvgbKTFqhRSZC0GTKZBjREEOwW97vUmGZA9PDYkivJUOdSbGjoN4pjK2xeJv2KDwSvMTsnbfGTUxidc0ibajrukrgshYl4i6D95cEdEsZA6bh
whatsapp.phone.number.id=1053051974550089