spring.datasource.url=jdbc:mysql://localhost:3306/estampaider
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# CORS
spring.mvc.dispatch-options-request=true

# WhatsApp
whatsapp.verify.token=estampaider_token_123
whatsapp.access.token=EAASnxhVhq6UBRMdcvMn7Q7GxdKW0RKyOqjooVtmdfLpR8UYFMgFLiOUVemALwpQ2fjqoIqAt7NHWiGT51FA3DAZC1HmpVlFSQ65mY7aRY2EZA7y56deGc3VtNhqI2zeQYzwpj28rl9sCocoWdtlHguKzEA41eBKcvfjRj860CDHnfPYZCLciEVZA4ZCufLS58p5kPUfGHFThaMazBWgxDYNwxbasXFrZA4PiZAgZCrg32j9Srvv4sDCxqVVQZAPOj1EaXQLdxiznQXAIXrNKK8MGs
whatsapp.phone.number.id=1039205345948798